name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      JWT_SECRET: # ADD SECRET PATH
      SENDGRID_API_KEY: # ADD SENDGRID API KEY
    strategy:
      matrix:
        node_version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test

  e2e:
    runs-on: ubuntu-latest
    environment: testing
    env:
      JWT_SECRET: # ADD SECRET PATH
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose up --abort-on-container-exit

  deploy:
    needs: [ test, e2e ] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.11.10
      with:
          heroku_api_key: #ADD HEROKU API KEY
          heroku_app_name: #HEROKU APP NAME 
          heroku_email: #ADD HEROKU EMAIL 
